import Head from 'next/head'
import Image from 'next/image'
import Main from './home';
import React, { useState, useEffect } from 'react'

export default function Home() {
  const [open, setOpen] = useState(false)
  // useEffect(() => {
  //   window.addEventListener('resize', updateSize);
  //   updateSize()
  //   return () => window.removeEventListener('resize', updateSize);
  // }, [open])

  // const updateSize = () => {
  //   if (window.innerWidth < 768) {
  //     setOpen(false)
  //     window.location.replace("https://m.birzoom.uz");
  //   } else if (window.innerWidth > 768) {
  //     setOpen(true)
  //   }
  // }

  useEffect(()=>{
  //   let details = navigator.userAgent;
  //   console.log(details);
  //   let regexp = /android|iphone|kindle|ipad/i;
  //   let isMobileDevice = regexp.test(details);
  //   if (isMobileDevice) {
  //     console.log("You are using a Mobile Device");
  //     setOpen(false)
  //     window.location.replace("https://m.birzoom.uz");
  // } else {
  //     console.log("You are using Desktop");
  //     setOpen(true)
  // }
  if (window.innerWidth < 768) {
        setOpen(false)
        window.location.replace("https://m.birzoom.uz");
      } else if (window.innerWidth > 768) {
        setOpen(true)
      }
  },[])

  return (<>
    {open === true &&  <div>
      <Head>
        <title>birzoom</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <!-- Icon --> */}
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png"/>
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png"/>
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png"/>
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5"/>
        <meta name="msapplication-TileColor" content="#da532c"/>
        <meta name="theme-color" content="#ffffff"/>

        {/* <!-- Fonts --> */}
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet"></link>
      </Head> 
      <Main/>
    </div>}
    </>)
}
